//! Generated by capsule
//!
//! `main.rs` is used to define rust lang items and modules.
//! See `entry.rs` for the `main` function.
//! See `error.rs` for the `Error` type.

#![no_std]
#![cfg_attr(not(test), no_main)]

// define modules
mod entry;
mod error;
mod hash;

#[cfg(test)]
extern crate alloc;

#[cfg(not(test))]
use ckb_std::default_alloc;
#[cfg(not(test))]
ckb_std::entry!(program_entry);
#[cfg(not(test))]
default_alloc!(6 * 1024, 800 * 1024, 64);

/// program entry
pub fn program_entry() -> i8 {
    // Call main function and return error code
    ckb_std::debug!("into spore lua");
    match entry::main(ckb_std::env::argv()) {
        Ok(_) => 0,
        Err(err) => err.into(),
    }
}
